// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1  -triple riscv32 -target-feature +zihintpause -emit-llvm %s -o - \
// RUN:     | FileCheck %s

void pause()
{
    __builtin_riscv_pause(); // CHECK: call void @llvm.riscv.pause()
}
